### PR TITLE
Update README.md, fix example run command

### PR DESCRIPTION
**Pull request by federicobaldo**
Fix example command in readme.

Not sure if it is interesting to add also an example on how to monitor airbyte deploed via docker compose.

enter the db container
`docker exec -it airbyte-db /bin/bash`

access the pgsql in the db container
`psql -h 127.0.0.1 -p 5432 -U docker airbyte
`

Run airbyte exporter making sure it is connected to the docker airbyte internal network.
`docker run \
    --name airbyte-exporter \
    --rm \
    -e AIRBYTE_EXPORTER_DB_ADDR=airbyte-db:5432 \
    -e AIRBYTE_EXPORTER_DB_PASSWORD=<yourpassword> \
    -p 8090:8080 \
    --network="airbyte_airbyte_internal" \
    ghcr.io/botify-labs/airbyte_exporter:latest
`

### CODE REVIEW

**Comment by virtualtam** [comment]
Hi @federicobaldo, and thanks for the suggestions 👍 

As I am not working on this project anymore, maybe @SuperDormito or @ewjoachim could take a look at the PR (or forward it to the appropriate reviewers)?

**Comment by ewjoachim** [comment]
Indeed, I was not watching this repository, and now I do :)
@virtualtam: if you're interested, I think we may be able to have you retain permissions on this repo. Or we may be able to transfer ownership to you :)

@federicobaldo thanks for the contribution and sorry for the delay !

**Review by ewjoachim — APPROVED** [review]

**Comment by ewjoachim** [comment]
Ha, I also don't have the permissions to merge. I've filed a request, it's low priority, I'll merge in the next weeks (but then I'll be able to merge faster next time)

**Review by ewjoachim — APPROVED** [review]

**Review by ewjoachim — APPROVED** [review]

**Comment by ewjoachim** [comment]
Thanks you again :)

**Pull request merged**
